const dummy_Products = [
  {
    product_id: 1,
    title: "DailyObjects Burgundy Faux Leather Fatty Women's Tote Bag ",
    rating: 65,
    review: 12,
    cutoff: 2499,
    price: 1299,
    offer: 48,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/n/y/nykdaoj005001_1.jpg",
  },
  {
    product_id: 2,
    title:
      "DailyObjects Butterflies And Hibiscus Flowers - Trapeze Crossbody Bag",
    rating: 87,
    review: 18,
    price: 1099,
    cutoff: 1999,
    offer: 45,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/b/u/but-and-hib-flo-mck-trapeze__1.jpg",
  },
  {
    product_id: 3,
    title: "DailyObjects And Love What You Do Arch Crossbody Bag",
    rating: 69,
    review: 16,
    price: 1249,
    cutoff: 1999,
    offer: 38,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/n/y/nykdaoj005044.jpg",
  },
  {
    product_id: 4,
    title: "DailyObjects How to Chill Like A Cat - Trapeze Crossbody Bag",
    rating: 64,
    review: 11,
    price: 1099,
    cutoff: 1999,
    offer: 45,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/h/o/how-to-chi-lik-a-mck-trapeze__1.jpg",
  },
  {
    product_id: 5,
    title: "DailyObjects Ddrypp Zip Wallet",
    rating: 64,
    review: 8,
    price: 849,
    cutoff: 1999,
    offer: 58,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/d/d/ddrypp-jms-zip-wallet__1.jpg",
  },
  {
    product_id: 6,
    title: "DailyObjects Pass This On Fatty Tote Bag",
    rating: 61,
    review: 12,
    price: 1299,
    cutoff: 2499,
    offer: 48,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/n/y/nykdaoj002693__1_.png",
  },
  {
    product_id: 7,
    title: "DailyObjects Girl In Flowerland - Trapeze Crossbody Bag",
    rating: 58,
    review: 11,
    price: 1099,
    cutoff: 1999,
    offer: 45,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/g/i/gir-in-flo-anh-trapeze__1.jpg",
  },
  {
    product_id: 8,
    title: "DailyObjects Silver Metallic Fatty Tote Bag",
    rating: 53,
    review: 12,
    price: 2499,
    cutoff: 1299,
    offer: 48,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/n/y/nykdaoj002722_1_.png",
  },
  {
    product_id: 9,
    title: "DailyObjects Mustard Flowers - Orbis Crossbody Bag",
    rating: 58,
    review: 11,
    price: 1149,
    cutoff: 2499,
    offer: 54,
    img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/8/1/81f2445must-flow-dob-orbis-crossbody-bag.jpg",
  },
];

export { dummy_Products };
